### ISSUE TITLE
proxy参数无法使用

### ISSUE THREAD

**Issue by Weoworks** [SoraRoseous/ChatSydney-react#16]
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/108215869/e0178ed9-862c-4e4b-82df-3cf11039d198)
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/108215869/fcb2630d-45cd-43cc-8891-49b664b860ce)

**Comment by SoraRoseous** [comment]
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/54582495/ea162139-6138-40b2-bed8-af9ad6ca6d60)
代码l里不是有socks5嘛

**Comment by Weoworks** [comment]
> ![image](https://user-images.githubusercontent.com/54582495/260766844-ea162139-6138-40b2-bed8-af9ad6ca6d60.png) 代码l里不是有socks5嘛

socks5和socks5h都试过了，依然server disconnected

**Comment by SoraRoseous** [comment]
报的啥错哇

**Comment by Weoworks** [comment]
> 报的啥错哇

草，稍等，我给程序写了个systemctl指定了一个sh文件挂后台了，我手动运行看看

**Comment by Weoworks** [comment]
> 报的啥错哇

对不起，不好意思，麻烦你了，又正常了，就是IP不行，打扰你了，打扰你了
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/108215869/17784cd4-ce51-420a-9735-32d5cfb359a4)
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/108215869/f5deff17-f783-4e06-91d6-a2a2555a7f67)

**Comment by SoraRoseous** [comment]
没事😂

**Comment by Weoworks** [comment]
紫砂😶
