### ISSUE TITLE
疯狂显示认证失败，IP被拉黑了？http代理无法使用

### ISSUE THREAD

**Issue by Weoworks** [SoraRoseous/ChatSydney-react#17]
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/108215869/6ad8a025-242c-4b90-bbc7-79aade5e7a97)
快疯了，http无法使用和我上一个提出的不能使用socks5代理一样，真的快疯啦!

**Comment by Weoworks** [comment]
起初接入一个warp可以继续使用但是现在不行了

**Comment by Weoworks** [comment]
没事了，就是IP被拉黑了

**Comment by SoraRoseous** [comment]
一般更换ip就行了，但是换ip又得验证，反正是挺折磨人的，我已经习惯了。而且也有可能会是账号cookie的原因导致的

**Comment by Weoworks** [comment]
> 一般更换ip就行了，但是换ip又得验证，反正是挺折磨人的，我已经习惯了。而且也有可能会是账号cookie的原因导致的

很离谱就是了.......
