### ISSUE TITLE
对话报错anyio._backends._asyncio.ExceptionGroup: 4 exceptions were raised in the task

### ISSUE THREAD

**Issue by reece00** [SoraRoseous/ChatSydney-react#2]
全局代理谷歌访问正常。是我配置问题还是现在要tcp代理？还有网页上那个_u和json文件什么关系，是覆盖掉文件的u参数？
"anyio._backends._asyncio.ExceptionGroup: 4 exceptions were raised in the task group:\n----------------------------\nTraceback (most recent call last):\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\anyio\\_core\\_sockets.py\", line 164, in try_connect\n    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1691, in connect_tcp\n    await get_running_loop().create_connection(\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1085, in create_connection\n    raise exceptions[0]\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1069, in create_connection\n    sock = await self._connect_sock(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 973, in _connect_sock\n    await self.sock_connect(sock, address)\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\proactor_events.py\", line 726, in sock_connect\n    return await self._proactor.connect(sock, address)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\windows_events.py\", line 846, in _poll\n    value = callback(transferred, key, ov)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\...

**Comment by SoraRoseous** [comment]
你得确保你所有的流量都走的代理才行，clash的话开启tun模式就可以了。网页上那个_U cookie 就是填json文件里name=_U的value的值就可以了
