### ISSUE TITLE
huggingface部署出现如下问题

### ISSUE THREAD

**Issue by Propny** [SoraRoseous/ChatSydney-react#25]
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/140315524/3403e992-2e9d-4d45-b573-703f9c507db6)
请问怎么解决，谢谢

**Comment by SoraRoseous** [comment]
你如果确定你的cookie是正确的，那多半就是你这个云平台的ip被微软封了，换一个吧

**Comment by Propny** [comment]
ok.
