### ISSUE TITLE
对话网页报错

### ISSUE THREAD

**Issue by zhayuchuan** [SoraRoseous/ChatSydney-react#3]
"Traceback (most recent call last):\n  File \"C:\\ChatSydney-react-react\\main.py\", line 28, in sydney_process_message\n    async for _, response in chatbot.ask_stream(prompt=user_message, conversation_style=\"creative\", raw=True,\n  File \"C:\\ChatSydney-react-react\\SydneyGPT\\SydneyGPT.py\", line 30, in ask_stream\n    async for key, value in super().ask_stream(*args, **kwargs):\n  File \"C:\\ChatSydney-react-react\\EdgeGPT\\EdgeGPT.py\", line 186, in ask_stream\n    async for response in self.chat_hub.ask_stream(\n  File \"C:\\ChatSydney-react-react\\SydneyGPT\\SydneyGPT.py\", line 55, in ask_stream\n    async for key, value in super().ask_stream(*args, **kwargs):\n  File \"C:\\ChatSydney-react-react\\EdgeGPT\\chathub.py\", line 104, in ask_stream\n    async with connect(\n  File \"C:\\Users\\30961\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\websockets\\legacy\\client.py\", line 637, in __aenter__\n    return await self\n           ^^^^^^^^^^\n  File \"C:\\Users\\30961\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\websockets\\legacy\\client.py\", line 655, in __await_impl_timeout__\n    return await self.__await_impl__()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\30961\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\websockets\\legacy\\client.py\", line 662, in __await_impl__\n    await protocol.handshake(\n  File \"C:\\Users\\30961\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\websockets\\legacy\\client.py\", line 329, in handshake\n    raise InvalidStatusCode(status_code,response_headers)\nwebsockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200\n"
clash开的tun模式

**Comment by SoraRoseous** [comment]
检查一下clash日志，看看这两条连接是不是都走的代理，下面那个地址是DNS解析之后的sydney.bing.com的ip，每次可能都不一样，但是查一下的话也是微软的ip
![image](https://github.com/SoraRoseous/ChatSydney-react/assets/54582495/d4369e7d-e71e-48c3-9fd7-d49ded0f379b)

**Comment by renqabs** [comment]
我用的windows clash 0.19.0，tun是好使的，0.19.0以上的版本的不行，也不知道怎么回事

**Comment by zhayuchuan** [comment]
> 检查一下clash日志，看看这两条连接是不是都走的代理，下面那个地址是DNS解析之后的sydney.bing.com的ip，每次可能都不一样，但是查一下的话也是微软的ip ![image](https://user-images.githubusercontent.com/54582495/251419967-d4369e7d-e71e-48c3-9fd7-d49ded0f379b.png)

**Comment by zhayuchuan** [comment]
> 检查一下clash日志，看看这两条连接是不是都走的代理，下面那个地址是DNS解析之后的sydney.bing.com的ip，每次可能都不一样，但是查一下的话也是微软的ip ![image](https://user-images.githubusercontent.com/54582495/251419967-d4369e7d-e71e-48c3-9fd7-d49ded0f379b.png)

![捕获](https://github.com/SoraRoseous/ChatSydney-react/assets/135732975/fcdea4aa-1a5e-42b9-bfee-cb8b9dea5eb2)
检查过应该是没啥问题，大佬你用的啥魔法啊

**Comment by SoraRoseous** [comment]
> > 检查一下clash日志，看看这两条连接是不是都走的代理，下面那个地址是DNS解析之后的sydney.bing.com的ip，每次可能都不一样，但是查一下的话也是微软的ip ![image](https://user-images.githubusercontent.com/54582495/251419967-d4369e7d-e71e-48c3-9fd7-d49ded0f379b.png)
> 
> ![捕获](https://user-images.githubusercontent.com/135732975/251461780-fcdea4aa-1a5e-42b9-bfee-cb8b9dea5eb2.PNG) 检查过应该是没啥问题，大佬你用的啥魔法啊

两块钱一个月的acyun
