### ISSUE TITLE
能不能写一个在vercel上面部署的例子

### ISSUE THREAD

**Issue by yangjianchuan** [SoraRoseous/ChatSydney-react#7]
你好，能不能写一个在vercel上面部署的例子，我试了一下没部署成功。

**Comment by SoraRoseous** [comment]
没用过vercel，你说一下没成功的原因是什么呢

**Comment by yangjianchuan** [comment]
不折腾vercel了，我换成使用服务器部署了
git clone https://github.com/SoraRoseous/ChatSydney-react.git
cd ChatSydney-react
docker build -t sydney .
docker run -it --rm  -p 80:65432  sydney
