### ISSUE TITLE
最新版本报错

### ISSUE THREAD

**Issue by huoshenw** [SoraRoseous/ChatSydney-react#9]
Traceback (most recent call last):
chatsydney |   File "/app/main.py", line 29, in sydney_process_message
chatsydney |     async for _, response in chatbot.ask_stream(prompt=user_message, conversation_style="creative", raw=True,
chatsydney |   File "/app/SydneyGPT/SydneyGPT.py", line 30, in ask_stream
chatsydney |     async for key, value in super().ask_stream(*args, **kwargs):
chatsydney |   File "/app/EdgeGPT/EdgeGPT.py", line 186, in ask_stream
chatsydney |     async for response in self.chat_hub.ask_stream(
chatsydney |   File "/app/SydneyGPT/SydneyGPT.py", line 55, in ask_stream
chatsydney |     async for key, value in super().ask_stream(*args, **kwargs):
chatsydney |   File "/app/EdgeGPT/chathub.py", line 214, in ask_stream
chatsydney |     raise Exception("请前往官网检查账号是否已达24小时对话次数上限或是需要点击验证。如果是,请更换账号cookie或者点击验证。Please go to the official website to check if your account has reached the 24-hour conversation limit or needs to click verification. If so, please change your account cookie or click verification.")
但是手动在网页上填入账号的U值 可以正常使用 同一个账号

**Comment by SoraRoseous** [comment]
我没太明白是是什么意思呢，你是想说在cookie.json里的cookie不能正常用，然后网页上的输入框里输入可以正常用是吗？

**Comment by huoshenw** [comment]
是的 同一个账号的cookie 写在cookie.json 就会报这个错误 如果是把U值填写在网页就正常用

**Comment by huoshenw** [comment]
> 你可以试试先把main.py里第27行的加号和后面的东西删掉然后试试呢 ![image](https://user-images.githubusercontent.com/54582495/255612648-0f47972d-52eb-49d6-b2d3-d693cf3e8a35.png) 我现在没在家，过几天我回去看看，不过我当时用好像没这个问题啊

可以了 谢谢大佬
